### ISSUE TITLE
error init when trying to run the calendar

### ISSUE THREAD

**Issue by hadiyazdi** [Vodolazkyi/VACalendar#4]
Trying to run the calendar in my app gives error at this line

```
public required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
```

**Comment by Vodolazkyi** [comment]
I have fixed it. try download it again, pod install and run

**Comment by hadiyazdi** [comment]
I still get the same errors

Also, to make sure I am running the updated version, I redownloaded the repo manually and ran the workspace, and still get the same errors

**Comment by Vodolazkyi** [comment]
Did you install the pod ?

**Comment by hadiyazdi** [comment]
yes

https://ibb.co/eF6Ddc

**Comment by Vodolazkyi** [comment]
try to clean your project and run again
